-- 设备
CREATE TABLE IF NOT EXISTS ssh_device (
  id        LONG                        GENERATED BY DEFAULT AS IDENTITY,
  orgId     long comment '企业Id',
  userId     long comment '用户Id',
  identifiy varchar(64) comment '设备标识',
  name      varchar(255) comment '设备名称',
  type      enum ('direct', 'callhome') default 'direct'
  comment '连接类型，直连，callhome',
  desc      varchar(255) comment '设备描述',
  ip        varchar(255) comment '设备IP',
  port      integer comment '设备端口',
  username  varchar(255) comment '认证用户名',
  password  clob comment '认证密码',
  PRIMARY KEY (id)
);
-- 用户
CREATE TABLE IF NOT EXISTS ssh_user (
  id       LONG                   GENERATED BY DEFAULT AS IDENTITY,
  username varchar(255) comment '用户名',
  password varchar(255) comment '密码',
  role     enum ('admin', 'user') default 'user'
  comment '用户角色，管理员，普通用户',
  salt char(32) not null  comment '盐，用于加密',
  enable   boolean comment '用户状态，启用，禁用',
  desc   varchar(255) comment '描述',
  PRIMARY KEY (id)
);
-- 组织机构
create table if not exists ssh_org (
  id     LONG GENERATED BY DEFAULT AS IDENTITY,
  name   varchar(255) comment '企业名称',
  desc   varchar(255) comment '企业描述',
  pId    long comment '父级Id',
  userId long comment '用户Id',
  PRIMARY KEY (id)
);