#!/usr/bin/env bash

echo "preparing ${project.name}"

getent group %{app_user_group} > /dev/null || groupadd -r %{app_user_group}
getent passwd %{app_user} > /dev/null || \
    useradd -r -d %{app_home} -g %{app_user_group} \
    -s /sbin/nologin -c "web ssh server" %{app_user}
exit 0